// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkNbdiJZs3afoAYns3VpPCQIBvA5J9Zc',
    appId: '1:261729773208:web:3a826c2aa85108f59052ed',
    messagingSenderId: '261729773208',
    projectId: 'global-confession',
    authDomain: 'global-confession.firebaseapp.com',
    storageBucket: 'global-confession.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaUuKTdmJ71yHdGxW0RIyCWebP7dkfXg',
    appId: '1:261729773208:android:26790af60927459a9052ed',
    messagingSenderId: '261729773208',
    projectId: 'global-confession',
    storageBucket: 'global-confession.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHfK8cl_XbkshY4KYsjYolGSyabu1aTY',
    appId: '1:261729773208:ios:89ed9d90c1e6ed849052ed',
    messagingSenderId: '261729773208',
    projectId: 'global-confession',
    storageBucket: 'global-confession.firebasestorage.app',
    iosBundleId: 'com.cyrus.globalConfession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHfK8cl_XbkshY4KYsjYolGSyabu1aTY',
    appId: '1:261729773208:ios:89ed9d90c1e6ed849052ed',
    messagingSenderId: '261729773208',
    projectId: 'global-confession',
    storageBucket: 'global-confession.firebasestorage.app',
    iosBundleId: 'com.cyrus.globalConfession',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkkNbdiJZs3afoAYns3VpPCQIBvA5J9Zc',
    appId: '1:261729773208:web:1b90a7d3ba53cd679052ed',
    messagingSenderId: '261729773208',
    projectId: 'global-confession',
    authDomain: 'global-confession.firebaseapp.com',
    storageBucket: 'global-confession.firebasestorage.app',
  );
}
